### ISSUE TITLE
use cors for potential spam prevention

### ISSUE THREAD

**Issue by pketh** [oilstel/gossips-cafe#1]
it looks like you can slightly harden app.js against the a spam bot attack that tries to post like 50 times in a second with `cors` which you can configure to return a `429` error to an ip that's making POST requests more than n times in a period of time.

for kinopio, after trying a couple approaches, I use the https://www.npmjs.com/package/cors

you should be able to get away with something like this in `app.js`:

```
import cors from 'cors'

app.use(cors(options))
app.options('*', cors(options)) // enables cors to be active on DELETE requests, but may not be relevant for the café

const globalLimiter = rateLimit({
  windowMs: 1000,
  max: 5 // limit each IP to 5 requests per second
})
app.use(globalLimiter)

// then the normal app.listen stuff
```

**Comment by oilstel** [comment]
oh that's a good idea. didn't know that was possible. just added a rate limiter 🍃

thanks for the advice!
